# Generated by Django 6.1.1 on 2026-09-30 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventorySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('accessed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Force',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('force_type', models.CharField(choices=[('ARMOURED', 'Armoured')], default='ARMOURED', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forces', to='forces.country')),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('platform_type', models.CharField(choices=[('MBT', 'Main Battle Tank'), ('IFV', 'Infantry Fighting Vehicle'), ('APC', 'Armoured Personnel Carrier'), ('ATGM_CARRIER', 'ATGM Carrier'), ('MRAP', 'Mine Resistant Ambush Protected'), ('LIGHT_ARMOURED', 'Light Armoured Vehicle'), ('RECON', 'Reconnaissance'), ('OTHER', 'Other')], max_length=30)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('crew_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('passenger_capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('width_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('combat_weight_tonnes', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('engine_power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('operational_range_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fuel_capacity_litres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mobility_class', models.CharField(blank=True, help_text='Simulation mobility category.', max_length=50)),
                ('amphibious', models.BooleanField(default=False)),
                ('night_capable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('source_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platforms', to='forces.inventorysource')),
            ],
            options={
                'ordering': ['platform_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ForcePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized_quantity', models.PositiveIntegerField(default=0)),
                ('is_available_for_scenario', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('force', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_inventory', to='forces.force')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='force_inventory', to='forces.platform')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protection_class', models.CharField(blank=True, max_length=50)),
                ('front_class', models.CharField(blank=True, max_length=50)),
                ('side_class', models.CharField(blank=True, max_length=50)),
                ('rear_class', models.CharField(blank=True, max_length=50)),
                ('top_class', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('platform', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protection', to='forces.platform')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forces.inventorysource')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('sensor_type', models.CharField(choices=[('OPTICAL', 'Optical'), ('THERMAL', 'Thermal'), ('RADAR', 'Radar'), ('LASER', 'Laser'), ('OTHER', 'Other')], max_length=30)),
                ('detection_range_m', models.PositiveIntegerField(blank=True, null=True)),
                ('identification_range_m', models.PositiveIntegerField(blank=True, null=True)),
                ('night_capable', models.BooleanField(default=False)),
                ('weather_degradation', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forces.inventorysource')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_primary', models.BooleanField(default=False)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_sensors', to='forces.platform')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platforms', to='forces.sensor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='force',
            constraint=models.UniqueConstraint(fields=('country', 'code'), name='unique_force_code_per_country'),
        ),
        migrations.AddConstraint(
            model_name='forceplatform',
            constraint=models.UniqueConstraint(fields=('force', 'platform'), name='unique_platform_per_force'),
        ),
        migrations.AddConstraint(
            model_name='platformsensor',
            constraint=models.UniqueConstraint(fields=('platform', 'sensor'), name='unique_sensor_per_platform'),
        ),
    ]
