# Generated by Django 6.1.1 on 2026-09-30 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForcePlayerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('force', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_assignments', to='forces.force')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='force_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'force'],
                'constraints': [models.UniqueConstraint(fields=('user', 'force'), name='unique_force_player_assignment')],
            },
        ),
    ]
