# Generated by Django 6.1.1 on 2026-09-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattleOrbat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.PositiveIntegerField(blank=True, help_text='ID of the exercise associated with this ORBAT.', null=True)),
                ('battle_id', models.PositiveIntegerField(blank=True, help_text='ID of the battle associated with this ORBAT.', null=True)),
                ('master_orbat', models.JSONField(blank=True, default=dict)),
                ('playing_orbat', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
