# Generated by Django 6.1.1 on 2026-10-01 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forces', '0002_forceplayerassignment'),
        ('scenarios', '0002_exercise_battle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battleorbat',
            name='battle_id',
        ),
        migrations.RemoveField(
            model_name='battleorbat',
            name='exercise_id',
        ),
        migrations.AddField(
            model_name='battleorbat',
            name='battle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orbat', to='scenarios.battle'),
        ),
        migrations.AddField(
            model_name='battleorbat',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_orbats', to='scenarios.exercise'),
        ),
        migrations.CreateModel(
            name='BattleForce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BLUE', 'Blue'), ('RED', 'Red')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_forces', to='scenarios.battle')),
                ('force', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='battle_participations', to='forces.force')),
            ],
            options={
                'ordering': ['battle', 'side', 'force'],
                'constraints': [models.UniqueConstraint(fields=('battle', 'force'), name='unique_force_per_battle')],
            },
        ),
    ]
