# Generated by Django 6.1.1 on 2026-10-01 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_remove_battleorbat_battle_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleorbat',
            name='battle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orbat', to='scenarios.battle'),
        ),
        migrations.AlterField(
            model_name='battleorbat',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_orbats', to='scenarios.exercise'),
        ),
    ]
