# Generated by Django 6.0.4 on 2026-10-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0004_alter_battleorbat_battle_alter_battleorbat_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=3600, help_text='Maximum battle duration in seconds.'),
        ),
        migrations.AddField(
            model_name='battle',
            name='random_seed',
            field=models.PositiveBigIntegerField(blank=True, help_text='Seed used for deterministic simulation behaviour.', null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='tick_interval_ms',
            field=models.PositiveIntegerField(default=1000, help_text='Simulation tick interval in milliseconds.'),
        ),
    ]
