# Generated by Django 6.0.4 on 2026-10-05 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0005_battle_duration_seconds_battle_random_seed_and_more'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('side', models.CharField(choices=[('BLUE', 'Blue'), ('RED', 'Red')], max_length=10)),
                ('objective_type', models.CharField(choices=[('HVT', 'High Value Target'), ('PRIMARY', 'Primary Objective'), ('SECONDARY', 'Secondary Objective')], default='HVT', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DAMAGED', 'Damaged'), ('DESTROYED', 'Destroyed'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='scenarios.battle')),
                ('unit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objective', to='units.unit')),
            ],
            options={
                'ordering': ['battle', 'side', 'priority'],
            },
        ),
    ]
