# Generated by Django 6.0.4 on 2026-10-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='altitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='objective',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
