# Generated by Django 6.0.4 on 2026-10-05 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forces', '0002_forceplayerassignment'),
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DAMAGED', 'Damaged'), ('IMMOBILISED', 'Immobilised'), ('DESTROYED', 'Destroyed')], default='ACTIVE', max_length=20)),
                ('health', models.FloatField(default=100.0)),
                ('morale', models.FloatField(default=100.0)),
                ('fuel', models.FloatField(default=100.0)),
                ('ammunition', models.JSONField(blank=True, default=dict)),
                ('is_hvt', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='formations.formation')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='battle_units', to='forces.platform')),
            ],
            options={
                'ordering': ['formation', 'name'],
                'constraints': [models.UniqueConstraint(fields=('formation', 'name'), name='unique_unit_name_per_formation')],
            },
        ),
    ]
