# Generated by Django 6.0.4 on 2026-10-05 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='health',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='morale',
        ),
        migrations.CreateModel(
            name='UnitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('MOVE', 'Move'), ('HOLD', 'Hold'), ('ATTACK', 'Attack'), ('DEFEND', 'Defend'), ('RECON', 'Recon'), ('SUPPORT', 'Support'), ('WITHDRAW', 'Withdraw')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('target_latitude', models.FloatField(blank=True, null=True)),
                ('target_longitude', models.FloatField(blank=True, null=True)),
                ('target_altitude', models.FloatField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('target_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_by_orders', to='units.unit')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='units.unit')),
            ],
            options={
                'ordering': ['-priority', '-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(default=0.0, help_text='Heading in degrees.')),
                ('speed', models.FloatField(default=0.0, help_text='Current speed in metres per second.')),
                ('is_moving', models.BooleanField(default=False)),
                ('is_immobilised', models.BooleanField(default=False)),
                ('health', models.FloatField(default=100.0)),
                ('morale', models.FloatField(default=100.0)),
                ('fuel', models.FloatField(default=100.0)),
                ('is_detected', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='units.unit')),
            ],
        ),
    ]
