# Generated by Django 6.0.4 on 2026-10-05 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0005_battle_duration_seconds_battle_random_seed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('current_tick', models.PositiveBigIntegerField(default=0)),
                ('elapsed_seconds', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('battle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulation', to='scenarios.battle')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick_number', models.PositiveBigIntegerField()),
                ('elapsed_seconds', models.FloatField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('units_processed', models.PositiveIntegerField(default=0)),
                ('events_created', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='simulation.simulation')),
            ],
            options={
                'ordering': ['tick_number'],
                'constraints': [models.UniqueConstraint(fields=('simulation', 'tick_number'), name='unique_tick_per_simulation')],
            },
        ),
    ]
