# Generated by Django 6.1.1 on 2026-09-30 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ammunition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('ammunition_type', models.CharField(choices=[('KINETIC', 'Kinetic'), ('CHEMICAL', 'Chemical Energy'), ('HE', 'High Explosive'), ('ATGM', 'Anti-Tank Guided Missile'), ('AP', 'Armour Piercing'), ('OTHER', 'Other')], max_length=30)),
                ('caliber_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_notes', models.TextField(blank=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ammunition', to='forces.inventorysource')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('weapon_class', models.CharField(choices=[('KINETIC', 'Kinetic'), ('CHEMICAL', 'Chemical Energy'), ('AUTOCANNON', 'Autocannon'), ('ARTILLERY', 'Artillery'), ('MISSILE', 'Missile'), ('MACHINE_GUN', 'Machine Gun'), ('OTHER', 'Other')], max_length=30)),
                ('caliber_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('barrel_length_calibers', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('effective_range_m', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_range_m', models.PositiveIntegerField(blank=True, null=True)),
                ('rate_of_fire_rpm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('reload_time_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('stabilized', models.BooleanField(default=False)),
                ('fire_control_system', models.CharField(blank=True, max_length=150)),
                ('day_sight', models.BooleanField(default=False)),
                ('night_sight', models.BooleanField(default=False)),
                ('thermal_sight', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapons', to='forces.inventorysource')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_primary', models.BooleanField(default=False)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_weapons', to='forces.platform')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platforms', to='weapons.weapon')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('platform', 'weapon'), name='unique_weapon_per_platform')],
            },
        ),
        migrations.CreateModel(
            name='WeaponAmmunition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized_quantity', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('ammunition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weapons', to='weapons.ammunition')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ammunition_types', to='weapons.weapon')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('weapon', 'ammunition'), name='unique_ammunition_per_weapon')],
            },
        ),
    ]
