# Generated by Django 6.0.4 on 2026-10-05 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0005_battle_duration_seconds_battle_random_seed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleTerrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('terrain_asset_id', models.CharField(blank=True, max_length=100)),
                ('imagery_asset_id', models.CharField(blank=True, max_length=100)),
                ('min_longitude', models.FloatField(blank=True, null=True)),
                ('min_latitude', models.FloatField(blank=True, null=True)),
                ('max_longitude', models.FloatField(blank=True, null=True)),
                ('max_latitude', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('battle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terrain', to='scenarios.battle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BLUE', 'Blue'), ('RED', 'Red')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('polygon', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_zones', to='scenarios.battle')),
            ],
            options={
                'ordering': ['battle', 'side', 'name'],
                'constraints': [models.UniqueConstraint(fields=('battle', 'side'), name='unique_deployment_zone_per_side')],
            },
        ),
    ]
