# Generated by Django 6.0.4 on 2026-10-05 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0004_alter_battleorbat_battle_alter_battleorbat_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('formation_type', models.CharField(choices=[('ALPHA_ASSAULT', 'ALPHA Assault'), ('BRAVO_HVT_DEFENCE', 'BRAVO HVT Defence'), ('CHARLIE_FIRE_SUPPORT', 'CHARLIE Fire Support'), ('DELTA_RECON', 'DELTA Recon'), ('RED_ASSAULT', 'RED Assault'), ('RED_DEFENCE', 'RED Defence'), ('RED_FLANK', 'RED Flank'), ('RED_SUPPORT', 'RED Support')], max_length=40)),
                ('doctrine', models.CharField(blank=True, choices=[('AGGRESSIVE', 'Aggressive'), ('FLANKING', 'Flanking'), ('SUPPRESSIVE', 'Suppressive'), ('DEFENSIVE', 'Defensive')], max_length=20)),
                ('is_ai_controlled', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='scenarios.battle')),
                ('battle_force', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='scenarios.battleforce')),
            ],
            options={
                'ordering': ['battle', 'name'],
                'constraints': [models.UniqueConstraint(fields=('battle', 'name'), name='unique_formation_name_per_battle')],
            },
        ),
    ]
